name: Banking ETL

on:
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: banking
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client

      - name: Install Dependencies
        run: |
          pip install pandas
          pip install sqlalchemy
          pip install mysql-connector-python
          pip install faker
          pip install google-cloud-bigquery
          pip install pyarrow
          pip install pymysql
          pip install pandas-gbq

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL..."
          for i in {1..60}; do
            mysql -h 127.0.0.1 -u root -proot -e "SELECT 1" && break
            echo "Still waiting..."
            sleep 2
          done

      - name: Create Tables
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -proot banking < sql/schema.sql

      - name: Generate Data
        run: |
          python scripts/generate_data.py

      - name: Load Data to MySQL
        run: |
          python scripts/load_mysql.py

      - name: Test MySQL Connection
        run: |
          mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"
      - name: Print Transform Connection
        run: |
          grep -n "create_engine" scripts/transform.py
          cat scripts/transform.py | grep "127.0.0.1"
      - name: Check MySQL Tables
        run: |
           mysql -h 127.0.0.1 -u root -proot banking -e "SHOW TABLES;"

      - name: Debug Transform
        run: |
          python -u scripts/transform.py

      - name: Run Transformation
        run: |
          python scripts/transform.py

      - name: Load to BigQuery
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          python scripts/load_bigquery.py